name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Who to greet
        required: true
jobs:
    job1:
        name: chetan
        runs-on: ubuntu-latest
        steps:
        - if: ${{ github.event.inputs.name == 'chetan' }}
          run: echo "Hi! chetan this side."

    job2:
        name: pawan
        runs-on: ubuntu-latest
        steps:
        - if: ${{ github.event.inputs.name == 'pawan' }}
          run: echo "Hi! pawan this side."
