name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - chetan1
        - pawan

jobs:
  test-conditions:
    runs-on: ubuntu-latest

    steps:
      - name: simple evaluation on chetan1
        if: github.input == 'chetan1'
        run: echo "chetan kumar"

      - name: simple evaluation on pawan
        if: github.input == 'pawan'
        run: echo "pawan kumar"

      
