name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Who to greet
        required: true
jobs:
  greet:
     runs-on: ubuntu-latest
     
     steps:
     - if: ${{ github.event.inputs.name == 'chetan' }}
       run: echo "Hi! chetan this side."
     - if: ${{ github.event.inputs.name == 'pawan' }}
       run: echo "Hi! pawan this side."
