name: Conditional job Selection based on input

on:      
  workflow_dispatch:
    inputs:
      job-name:
        description: 'Job id'
        required: true

jobs:
  build:
    name: build
    if: ${{ github.event.inputs.job-name == 'build' }}
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2
    
    - name: echo
      run: |
       echo "this is build job" 
     

    - name: Other steps 
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
        
  release:
    name: release
    if: ${{ github.event.inputs.job-name == 'release' }}
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v2
    
    - name: echo
      run: |
       echo "this is release job" 
     

    - name: Other steps1
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'adopt'
