on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select the Environment'
        type: choice
        required: true
        options:
        - SIT
        - UAT
      op:
        description: 'Deploy or Delete Apps'
        type: choice
        required: true
        options:
        - Deploy
        - Delete
      ver:
        description: 'Type the app version'
        required: true
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }}  ${{ github.event.inputs.name }}"
