name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - chetan
        - pawan
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
     # environment:
      #  type: environment

jobs:
  greet:
     runs-on: ubuntu-latest
     
     steps:
     - if: ${{github.event.name == 'chetan'}}
       run: echo "${{ github.event.inputs.message }} echo "Hi! chetan this side."
     - if: ${{github.event.name == 'pawan'}}
       run: echo "${{ github.event.inputs.message }} echo "Hi! pawan this side."
