name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - chetan
        - pawan
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
     # environment:
      #  type: environment

jobs:
  if: github.event.input== 'chetan'
  runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} echo "Hi! chetan this side."
   if: github.event.input== 'pawan'
  runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} echo "Hi! pawan this side."
