name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - chetan
        - pawan
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
     # environment:
      #  type: environment

jobs:
  test-conditions:
    runs-on: ubuntu-latest

    steps:
      - name: hii this side chetan
        if: github.event.input == 'chetan'
        run: echo "runs"

      - name: simple evaluation on test
        if: github.event.input == 'pawan'
        run: echo "runs"
  
