name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Who to greet
        required: true
jobs:
    job1:
        name: chetan
        if: github.event.inputs.name == 'chetan'
        runs-on: ubuntu-latest
        steps:
        - run: echo "Hi! chetan this side."

    job2:
        name: pawan
        if: github.event.inputs.name == 'pawan'
        runs-on: ubuntu-latest
        steps:
         - run: echo "Hi! pawan this side."
         
    job3:
        if: ${{ always() }}
        runs-on: ubuntu-latest
        needs: [job1, job2]
